Lanways/twitter-api-2020

app.js, controllers/apis/admin-controller.js, controllers/apis/user-controller.js, middleware/api-auth.js, middleware/error-handler.js, routes/index.js, routes/modules/admin.js
功能1: admin登入功能，非admin不能登入
功能2: 非admin不能登入一般使用者頁面
=> feat: create admin login api

config/passport.js, controllers/apis/tweet-controller.js
feat: get tweets add Like and reply data
=> feat: get tweets add Like and reply data

controllers/apis/tweet-controller.js
feat: add RepliesCount and LikesCount
=> feat: add RepliesCount and LikesCount

controllers/apis/admin-controller.js, controllers/apis/tweet-controller.js, middleware/api-auth.js, package-lock.json, routes/index.js, routes/modules/admin.js
create feature/admin-tweets-api
=> feat: create feature/admin-tweets-api

controllers/apis/admin-controller.js, routes/modules/admin.js
=> feat: add deleteTweet api

config/passport.js, controllers/apis/admin-controller.js, models/user.js, routes/modules/admin.js
=> feat: add getUsers api

routes/index.js
=> feat: modify router

controllers/apis/admin-controller.js, controllers/apis/tweet-controller.js, models/like.js, models/reply.js, models/tweet.js, models/user.js, routes/index.js, test/requests/reply.spec.js, test/requests/tweet.spec.js
=> feat: modify api

controllers/apis/user-controller.js
feat: feature/add-tweet-user-to-replied_tweets-api
=> feat: feature/add-tweet-user-to-replied_tweets-api

controllers/apis/user-controller.js
=> feat: debug/getUserTweets-api

controllers/apis/user-controller.js
fea: featuer/singin-add-follow-count
=> feat: featuer/singin-add-follow-count

controllers/apis/user-controller.js
=> feat: modify getUserLikes api

controllers/apis/user-controller.js
=> feat: modify getUserFollowers api

controllers/apis/user-controller.js
=> feat: add avatar data

controllers/apis/user-controller.js
add isLiked to getUserTweets api
=> feat: add isLiked to getUserTweets api

controllers/apis/user-controller.js
feat:feature/addFollowing-api-add-CannotFollowOneself
=> feat:feature/addFollowing-api-add-CannotFollowOneself

seeders/20230607172308-user-seed-file.js
=> feat: feature/user-avatar

seeders/20230617051747-followship-seed-file.js
=> feat: add followship seed

controllers/apis/tweet-controller.js, controllers/apis/user-controller.js
add new Promis to postTweet and postReply
=> feat: add new Promis to postTweet and postReply

app.js
=> feat: feature/core-set

app.js
=> feat: set cros

app.js
=> feat: feature/set-cros

app.js
=> seted-cors

app.js, controllers/apis/tweet-controller.js
=> feat: feature/getTweets-add-isLiked

controllers/apis/tweet-controller.js
=> feat: feature/getTweets-add-user-id

package-lock.json, package.json, seeders/20230624110828-like-seed-file.js
=> feat: feature/add-like-seed

controllers/apis/user-controller.js, models/tweet.js
feature/set-delete-tweet-delete-foreignkey
=> feat: feature/set-delete-tweet-delete-foreignkey

controllers/apis/user-controller.js
=> feat: modify/signUp-role

controllers/apis/user-controller.js
feat: modify/signUp-introduction-check
=> feat: modify/signUp-introduction-check

controllers/apis/user-controller.js
modify currentUserIsLiked to getUserLikes api response data
=> feat: modify currentUserIsLiked to getUserLikes api response data

controllers/apis/user-controller.js
新增res data isfollowed 到addFollowing 及 removeFollowing api
=> feat: add isfollowed to addFollowing & removeFollowing api

controllers/apis/user-controller.js
=> feat: delete default banner from signup api
